# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    timeout-minutes: 4

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]

    runs-on: ${{ matrix.os }} 

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: "itsasekret_ci_6g9b75t2gt528az"
          MYSQL_DATABASE: "senecatest_ci_578gw9f6wf7"

        # NOTE: This is a healthcheck.
        #
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: mysql "${CI_DB_NAME}" --host="${CI_DB_HOST}" --user="${CI_DB_USER}" --password="${CI_DB_PASSWORD}" --port="${CI_DB_PORT}" < ./test/support/db/seed/schema.sql
      env:
        CI_DB_NAME: "senecatest_ci_578gw9f6wf7"
        CI_DB_HOST: "127.0.0.1"
        CI_DB_USER: "root"
        CI_DB_PASSWORD: "itsasekret_ci_6g9b75t2gt528az"
        CI_DB_PORT: ${{ job.services.mysql.ports['3306'] }}
    - run: npm install
    - run: npm test
